### ISSUE TITLE
Support ST2

### ISSUE THREAD

**Issue by blopker** [Colorsublime/Colorsublime-Plugin#14]
Now that the plugin is greatly simplified supporting ST2 should be investigated.

**Comment by mustafababil** [comment]
For those who want to install it to Sublime Text 2, here are the commands:
```cd ~/Library/Application\ Support/Sublime\ Text\ 2/Packages/```
```git clone -b st2 https://github.com/Colorsublime/Colorsublime-Plugin.git```

But I have a question: Isn't it available to see the changes in realtime when going up and down in the theme list? I mean that isn't there a preview feature when hovering on a theme?

In my case, I can only see the new theme when I select it.

Thanks by the way.

**Comment by blopker** [comment]
Yes, this is expected behavior. ST2's API does not allow for the instant preview feature since it has no way of notifying me when the user changes selection. It really limits the utility for ST2, but there's nothing I can do about it unless they change the API :(

That being said, thanks for being brave and testing out this branch. It's still in alpha and I haven't done too much testing yet. I'm glad to hear works for the most part!

**Comment by blopker** [comment]
I've decided not to support ST2 due to time constraints. 

Cheers!
