### ISSUE TITLE
Themes sidebar will not be installed.

### ISSUE THREAD

**Issue by CassioGodinho** [Colorsublime/Colorsublime-Plugin#17]
I installed colorsublime via package manager. When I install the theme the color scheme is installed just fine but the sidebar wont.
Using sublime3 build 3065

**Comment by blopker** [comment]
Yeah, this is a slight nomenclature issue. Colorsublime really only manages schemes and not whole themes. There has been discussion around making this more clear, but we haven't reached a consensus. Sorry for the confusion.
