### ISSUE TITLE
Killed Package Manager

### ISSUE THREAD

**Issue by phillip-haydon** [Colorsublime/Colorsublime-Plugin#18]
So after installing this, it has killed the Package Manager.

Package Control no longer exists. Completely removed Sublime Text and re-installed, got it back, installed the package again, bam gone...

**Comment by blopker** [comment]
Interesting (sorry for the late response). Can you provide OS, SublimeText Version, any other info etc..?

I haven't heard of this issue before.

**Comment by phillip-haydon** [comment]
Windows 8.1, fully patched.
Sublime Text 3 (Dev build 3069)
Administrator setup as Windows Live account, no permission issues.

Basically I opened up Sublime Text, installed the Package Manager. Restarted ST, then installed the Colorsublime-Plugin.

Then I browsed all the themes, installed a few themes. Once installed I restarted ST to ensure it saved (because I wasn't convinced it was so easy)

That all worked perfectly. 0 issues.

Then went to install some other plugins. I pressed CTRL+SHIFT+P and typed Package... All the package control stuff was gone.

After fiddling around, reinstalling, etc I closed ST. Uninstalled from Programs. Navigated to the User directory for ST and deleted it to ensure all settings were removed.

Installed Package manager again, restart, install coloursublime again, restart, attempted to open the package manager, and it was gone. 

I repeated this one more time to ensure I'm not going insane. Same result.

I haven't tested on another machine yet. I can test on my work computer tomorrow to ensure it's not just an environment issue.

**Comment by blopker** [comment]
K, again, apologies, getting access to Windows is a little painful for me even with a VM.

I just followed your steps, but I can't replicate. Package Control is still there after Colorsublime install for me. Did you get a chance to try on another computer?

**Comment by blopker** [comment]
Also, are there any errors in the ST console? (View -> show console)

**Comment by blopker** [comment]
Cannot reproduce. Let me know if this is still an issue.
