### ISSUE TITLE
plugin no longer works

### ISSUE THREAD

**Issue by nmn** [Colorsublime/Colorsublime-Plugin#19]
I can remove and install colorsublime through package control, but it no longer works.

Specifically it no longer shows up in the commad+shift+P menu.

**Comment by blopker** [comment]
Hm, I just installed it with a fresh install in a VM (Windows 8.1) and it works fine for me.

Do you have more specifics on your setup? (OS, ST version, anything else)

**Comment by blopker** [comment]
Also anything interesting show up in the ST console? (view -> show console)

**Comment by nmn** [comment]
The problem was that colorsublime wasn't showing up in the menu. No errors in console. Working fine to switch existing themes from the preferences menu.

Yosemite, ST3

However, after a full restart, the problem seems to have fixed itself. This could be a bug in Sublime itself.

**Comment by blopker** [comment]
Hey, thank you for the report anyway. This seems to be a problem with ST plugins in general so the more info the better. :)
