### ISSUE TITLE
Error: Theme list not found

### ISSUE THREAD

**Issue by rafapaulin** [Colorsublime/Colorsublime-Plugin#22]
I am getting this error when trying to install themes via package control. Any insights?

thanks in advance

**Comment by blopker** [comment]
Works for me. You have to be connected to the internet. Also, some corporate proxies can get in the way.

Try:
1. Restarting Sublime Text, or even your whole computer
2. Ensuring you're connected to the internet
3. Try to install a theme again

**Comment by rafapaulin** [comment]
corporate proxy may be the problem. I did not thought about it because the package control works fine, so i thought this plugin would be the same.

any workaround?

**Comment by blopker** [comment]
I haven't been able to crack this one... There's an open ticket for it. What OS are you using?

**Comment by rafapaulin** [comment]
Windows 7
Via InoMail on Android-------- Original Message --------July 22, 2015 6:11:40 PM GMT-03:00, Bo Lopker <notifications@github.com> wrote:
I haven't been able to crack this one... There's an open ticket for it. What OS are you using?

**Comment by blopker** [comment]
OK, thank you for the report. Windows is the one OS I haven't been able to figure out. Mostly since I only have access to OSX and Linux. The problem is compounded since I also can't replicate the issue since I have no proxies. 

I'll reference this ticket with the original though: #2 

As always, I'm very open to pull requests if you have any ideas.

Cheers!

**Comment by rafapaulin** [comment]
Thank you! And keep the good work 
Via InoMail on Android-------- Original Message --------July 22, 2015 6:42:03 PM GMT-03:00, Bo Lopker <notifications@github.com> wrote:
OK, thank you for the report. Windows is the one OS I haven't been able to figure out. Mostly since I only have access to OSX and Linux. The problem is compounded since I also can't replicate the issue since I have no proxies. 

I'll reference this ticket with the original though: #2 

As always, I'm very open to pull requests if you have any ideas.

Cheers!
