### ISSUE TITLE
Semantics... (not really an issue)

### ISSUE THREAD

**Issue by Tracy-Tra** [Colorsublime/Colorsublime-Plugin#25]
Your system should really be changed - the names of these things I mean. You call them "Themes" when they are really not themes (entire UI for Sublime Text), but rather color schemes. 

Other than that, I do love the system. Sure makes it easy to change color schemes on the fly.

**Comment by GianlucaGuarini** [comment]
closing this issue for the same reason we have closed [this](https://github.com/Colorsublime/Colorsublime-Themes/issues/33) @Tracy-Tra thanks anyway

**Comment by Tracy-Tra** [comment]
Gotcha. I wasn't asking for the plugin to be changed, just documentation regarding could have a simple note at the top explaining the difference.... would probably help a LOT of people.... /shrug

**Comment by GianlucaGuarini** [comment]
@Tracy-Tra pull requests are welcome
