### ISSUE TITLE
No "colorsublime" in package control install for sublime 3.

### ISSUE THREAD

**Issue by nligon** [Colorsublime/Colorsublime-Plugin#27]
Screenshot shows all results searching for "colorsub". "Colorsublime" and "color sublime" produce nothing.

![screen shot 2016-03-07 at 12 56 11](https://cloud.githubusercontent.com/assets/16262893/13582991/008bc2cc-e464-11e5-98b2-fd5fa06d00bc.png)

**Comment by GianlucaGuarini** [comment]
maybe you have already it installed.. on my sublime everything works fine

**Comment by nligon** [comment]
You're right! It didn't show up until I switched to a theme unrelated to colorsublime. Then it appeared. Thanks!

**Comment by blopker** [comment]
No worries, thanks for using Colorsublime!
