### ISSUE TITLE
Customize colors of an installed theme

### ISSUE THREAD

**Issue by onirix** [Colorsublime/Colorsublime-Plugin#28]
Is it possible to edit a *.tmTheme file in "Packages/Colorsublime - Themes" ?

I’ve got this line in my "User/Preferences.sublime-settings"
    "color_scheme": "Packages/Colorsublime - Themes/TwoStones.tmTheme",

When I modify it, it doesn’t update colors in Sublime.

Any idea ?
Thx

**Comment by LKGames** [comment]
Sublime Text doesn't seem to update the theme as soon as it's changed. It usually updates it 'randomly' after a while of using the program. I'm guessing the themes are cached somewhere.

**Comment by blopker** [comment]
Huh, sorry for missing this...

Yes, there's no way to modify a theme and continue to receive updates for it. Your best bet is to copy the theme somewhere manually and edit it.
