### ISSUE TITLE
Plugin not working with 'Colorsublime: install theme,' also can't browse themes from menu

### ISSUE THREAD

**Issue by jason-mehmel** [Colorsublime/Colorsublime-Plugin#30]
I'm running BunsenLabs, a debian-based distro, on a Lenovo ThinkPad. I've upgrade SublimeText3 to 3124.

**Comment by blopker** [comment]
Hey, I haven't gotten any reports of the plugin not working for a while. Are there any interesting messages in the console? http://docs.sublimetext.info/en/latest/basic_concepts.html#sublime-text-is-programmable

**Comment by jason-mehmel** [comment]
You know, I'm not sure what happened. I upgraded Sublime Text one level higher (3126) and it now appears to be working!

**Comment by blopker** [comment]
Great! Please let me know if it stops working again. At the very least I'd like to improve the error messages.
