### ISSUE TITLE
Did you ever thought about making a Themesublime?

### ISSUE THREAD

**Issue by Droyk** [Colorsublime/Colorsublime-Plugin#33]
**_You are about to read some bad English and I am really sorry about it I am not a native English speaker._**
Hey developer I like colorsublime it really saves my time and it's easy to use  
but I was thinking is there is anyway you can make a ThemeSublime so that user just hove over a theme to see what it looks like. 
it's completely similar to color sublime the only difference is colorsublime changes the colors of the sublime and themesublime as you may have guessed it changes the theme of the sublime editor.

but I think you can't make this because of sublime editor themeing process everytime a user enable's a theme a user have to restart to make it completely compatible so I want to know is there is any way we can bypass this.

**1 idea I have thought is** 
Our option is let's make the hovering option seamless as possible and after user hit enter to install the theme they just have to restart the sublime editor  
for example 
let the user see what the theme looks like and then when the user hit enter for theme to install they just have to restart it after that.    

So what you think did I nail it I don't think so 🤔 but what I want to know is will you make or atleast even try it
thanx for reading it.

**Comment by blopker** [comment]
Hey Droyk, thank you for the feature request! We don't have full theme support on the roadmap and it's not something we're looking to support. Like you said Sublime does not have the APIs to do live theme switching so the plugin would have to be rewritten for this.

Thank you for your time. I'll keep this feature in mind, but it's not something we'll add any time soon.

Cheers!
