### ISSUE TITLE
Jump and Browse

### ISSUE THREAD

**Issue by sundarv85** [Colorsublime/Colorsublime-Plugin#34]
Hello,

After I have installed a theme, if I want to again start from that particular selection - how to do that,.

For e.g. when I installed Druid theme the Colorsublime drop down selection closed. Now if I want to again start from Druid, is it possible.

**Comment by blopker** [comment]
There isn't really a way in the ST API to do this. You could always skip to the 'D' themes by opening the install menu and typing 'd'.

Cheers!
