### ISSUE TITLE
Not finding Colorsublime

### ISSUE THREAD

**Issue by eriktobben** [Colorsublime/Colorsublime-Plugin#35]
Hi!

I am searching through Package Control -> Install package and I can't find Colorsublime. Is it gone?

**Comment by blopker** [comment]
Oh no!

Can you check two things for me?

The package won't show up if:
1. Colorsublime is already installed
2. You're running Sublime Text 2, and not 3

Lemme know if this is the case.

Cheers!

**Comment by eriktobben** [comment]
I'm so sorry. It was already installed. Thanks!
