### ISSUE TITLE
What is the "Run “Package Control: Install Package” command"

### ISSUE THREAD

**Issue by OyeBenny** [Colorsublime/Colorsublime-Plugin#36]
I'm trying to install this plugin. I have the python code I copy and pasted into the Sublime 3 console.
but all you guys have is `Run “Package Control: Install Package” command`.

sorry, I'm new.

**Comment by blopker** [comment]
Hey @OyeBenny, you've installed the package manager for Sublime Text: https://packagecontrol.io/

Next you have to run `Package Control: Install Package` then find ColorSublime and select it. Then you will have this plugin.
