### ISSUE TITLE
"Error loading colour scheme" (but it actually works)

### ISSUE THREAD

**Issue by avelican** [Colorsublime/Colorsublime-Plugin#48]
After installing the plugin, I can select all the themes through Sublime Text's own UI, but if I try to use the command "Colorsublime: Install Theme", selecting a theme gives me an error. The install does succeed, but it seems I need to restart Sublime for the new theme to take effect.

"Error loading colour scheme Packages/Colorsublime - Themes/1337.tmTheme: Unable to open Packages/Colorsublime - Themes/1337.tmTheme".

Looks like this repo hasn't been updated in 5 years, so maybe something broke with the new version of Sublime Text?

(Amusingly, all the themes are already downloaded in the cache folder, and I can select them through Sublime's UI without "installing" them, so the whole thing seems a bit strange (perhaps the functionality made more sense in an older version of Sublime?)

**Comment by blopker** [comment]
Looks like Sublime got too fast... I've added a small delay, so the filesystem has a chance to catch up before Sublime tries to load the theme.
